### ISSUE TITLE
AU915, join otaa denied

### ISSUE THREAD

**Issue by FedericoAndrades** [MicrochipTech/atsamr34_lorawan_rn_parser#10]
No consigo que transmita el SAMR34, envio los siguientes comandos, pero no llegan UpLinks al gateway.
 25/3/2021 23:09:15 [TX] - sys factoryRESET<CR><LF>
 25/3/2021 23:09:15 [RX] - <GS><SUB><ETB>7G<BEL>NW7WG<BEL>n<ETB>W7W§<SO>þ—7GW;N]fG<BEL>N]f¼W7Gø<SUB>÷;w]:n<GS>w¸·;u]ø<LF>
USER BOARD MLS_SDK_1_0_P_4 Mar 25 2021 23:06:30<CR><LF>
 25/3/2021 23:09:17 [TX] - mac reset AU915<CR><LF>
 25/3/2021 23:09:17 [RX] - ok<CR><LF>
 25/3/2021 23:09:18 [TX] - mac set deveui A5000003C1E3B83D<CR><LF>
 25/3/2021 23:09:18 [RX] - ok<CR><LF>
 25/3/2021 23:09:19 [TX] - mac set joineui 1111111111111111<CR><LF>
 25/3/2021 23:09:19 [RX] - ok<CR><LF>
 25/3/2021 23:09:19 [TX] - mac set appkey 01010101010101010101010101010101<CR><LF>
 25/3/2021 23:09:19 [RX] - ok<CR><LF>
 25/3/2021 23:09:20 [TX] - mac set edclass c<CR><LF>
 25/3/2021 23:09:20 [RX] - ok<CR><LF>
 25/3/2021 23:09:21 [TX] - mac set subband status 2 off<CR><LF>
 25/3/2021 23:09:21 [RX] - ok<CR><LF>
 25/3/2021 23:09:21 [TX] - mac set subband status 3 off<CR><LF>
 25/3/2021 23:09:21 [RX] - ok<CR><LF>
 25/3/2021 23:09:22 [TX] - mac set subband status 4 off<CR><LF>
 25/3/2021 23:09:22 [RX] - ok<CR><LF>
 25/3/2021 23:09:22 [TX] - mac set subband status 5 off<CR><LF>
 25/3/2021 23:09:22 [RX] - ok<CR><LF>
 25/3/2021 23:09:23 [TX] - mac set subband status 6 off<CR><LF>
 25/3/2021 23:09:23 [RX] - ok<CR><LF>
 25/3/2021 23:09:23 [TX] - mac set subband status 7 off<CR><LF>
 25/3/2021 23:09:23 [RX] - ok<CR><LF>
 25/3/2021 23:09:23 [TX] - mac set subband status 8 off<CR><LF>
 25/3/2021 23:09:24 [RX] - ok<CR><LF>
 25/3/2021 23:09:25 [TX] - mac join otaa<CR><LF>
 25/3/2021 23:09:25 [RX] - ok<CR><LF>
 25/3/2021 23:09:33 [RX] - denied<CR><LF>

**Comment by gd91** [comment]
not the place for technical support. check out www.microchip.com/support
