### ISSUE TITLE
Consistent Repeatable Join Error

### ISSUE THREAD

**Issue by baxterjo** [MicrochipTech/atsamr34_lorawan_rn_parser#12]
# Problem
I wrote a short python serial script to get the WLR089U0 module to join the following LoRaWAN network:
- Application Server: AWS IoT Core for LoRaWAN
- Gateway: Laird Sentrius RG191 LoRaWAN Gateway

The python script is as follows:
```python
import time

import serial

from factory_reset import factory_reset
from join_otaa import join_otaa
from send_command_with_response import send_command_with_response

lora_chip_port = "COM19"
lora_chip_baud = 115200
join_eui = "REDACTED"
app_key = "REDACTED"
wait_time = 35


def main():
    lora_device = serial.Serial(lora_chip_port, lora_chip_baud, timeout=10)
    lora_device.reset_input_buffer()
    lora_device.reset_output_buffer()
    factory_reset(lora_device)
    dev_eui = str(send_command_with_response(lora_device, "sys get hweui"))
    send_command_with_response(lora_device, "mac reset na915")
    send_command_with_response(lora_device, "mac get deveui")
    send_command_with_response(lora_device, f"mac set deveui {dev_eui}")
    send_command_with_response(lora_device, "mac get deveui")
    send_command_with_response(lora_device, f"mac set joineui {join_eui}")
    send_command_with_response(lora_device, f"mac set appkey {app_key}")

    while not join_otaa(lora_device):
        print(f"OTAA join failed, retrying in {wait_time} seconds...")
        time.sleep(35)

    lora_device.close()


if __name__ == "__main__":
    main()
```
`factory_reset()`, `join_otaa()`, and `send_command_with_response()` are just wrappers for the corresponding rn parser serial write/read functions.

Each time I run this script, the initial response from the module is that I was denied after attempting to join the first time, then when I retry after the join duty cycle time, it accepts. *But* if I issue any commands to the module *other than a join request* I will consistently be denied from joining the server. (i.e. issuing `mac get joindutycycletime` before attempting another `mac join otaa`, denied every time)

```shell
Issuing factory reset...
[UART RX] 
[UART RX] Last reset cause: System Reset Request
[UART RX] LoRaWAN Stack UP
[UART RX] USER BOARD MLS_SDK_1_0_P_5 Jun 18 2021 11:34:32
[UART TX] sys get hweui
[UART RX] REDACTED
[UART TX] mac reset na915
[UART RX] ok
[UART TX] mac get deveui
[UART RX] 0000000000000000
[UART TX] mac set deveui REDACTED
[UART RX] ok
[UART TX] mac get deveui
[UART RX] REDACTED
[UART TX] mac set joineui REDACTED
[UART RX] ok
[UART TX] mac set appkey REDACTED
[UART RX] ok
[UART TX] mac join otaa
[UART RX] ok
[UART RX] denied
OTAA join failed, retrying in 35 seconds...
[UART TX] mac join otaa
[UART RX] ok
[UART RX] accepted
```
In conclusion, the only time I am able to successfully join otaa is issuing two `mac join otaa` commands back to back, issuing no other commands and ensuring to wait more than the join duty cycle time in between `mac join otaa` commands.

# What I have tried
- Waiting for the joindutycycletime between setting up all of the otaa keys before attempting to join the first time
    - Still denied entry to the network, then after a second `joindutycycletime` waiting period, join request is accepted.
- Deleting the device from the application server and re-creating it
    - I tried this to force the server to recognize that the device disconnected, then there would be no duplicate deveui issues.
- Creating a brand new device (fresh deveui) in the application server
    - Same result as above
- After being denied the first time, I use `mac get joindutycycletime` to get the exact time remaining from the module before being able to attempt to join again.
    - This results in the module being consistently denied from joining the network.
# Possible Solution
I don't know what the repository looks like at the moment, but it seems like the module may only be able to transition to an `accepted` state when coming from a `denied` state.

**Comment by gd91** [comment]
Please use the case system for reporting an issue.
[https://microchipsupport.force.com/s/article/How-to-submit-a-case](https://microchipsupport.force.com/s/article/How-to-submit-a-case)
Thanks.
