### ISSUE TITLE
APPS_ENDDEVICE_DEMO1 Release build fails due to flawed header configuration

### ISSUE THREAD

**Issue by michaesc** [MicrochipTech/atsamr34_lorawan_rn_parser#5]
## Reproducibility

1. Download code
2. Open Microchip Studio
3. Open the solution
4. Change the project to APPS_ENDDEVICE_DEMO1
5. Change configuration to release
6. Build the project

## Problem

The build fails when the file parser.h is not found in the include path.

**Comment by gd91** [comment]
fixed release build
