### ISSUE TITLE
APPS_ENDDEVICE_DEMO1 Release build fails due to missing definition conditions

### ISSUE THREAD

**Issue by michaesc** [MicrochipTech/atsamr34_lorawan_rn_parser#7]
## Reproducibility

Download code
Open Microchip Studio
Open the solution
Change the project to APPS_ENDDEVICE_DEMO1
Change configuration to release
Build the project

## Problem

The build fails when code tries to use EDBG structures even when EDBG_EUI_READ is not set.

**Comment by gd91** [comment]
fixed release build
