### ISSUE TITLE
Is code equally good for WLR089 as for WLR089 Xplained Pro? 

### ISSUE THREAD

**Issue by ThingsOfficer** [MicrochipTech/atsamr34_lorawan_rn_parser#9]
I'm using this code for a standalone WLR089 module. 
I commented out some pin defintions (button and LEDs) and the button interrupt. 

Anyway I'm having trouble with this module at different stages. 

Right now I made it so far that the join procedure is as follows:

>> sys factoryRESET
<< System Reset Request
<< LoRaWAN Stack UP
<< USER BOARD MLS_SDK_1_0_P_5 ...
>> mac reset 868
<< ok
>> sys get hweui
<< 0123456789123456
>> mac set deveui 0123456789123456
<< ok
>> mac set joineui 0000000000000000
<< ok
>> mac set appkey abcd1234...
<< ok
>> mac join otaa
<< ok
(waiting some seconds)
<< denied

I have a gateway close by and I don't see any message from the device received there. 
(But other devices can be seen, so the gateway is working). 

I there something that I missed? Could it be a hardware fault?

I'm unsure if there are more problems when using WLR089 instead of the XPlained Pro Board. 
I lost two modules that suddenly seemed to heat up drawing 300 mA of current... so I'm not sure if there are some more pins I should reconfigure, or if I made a soldering mistake. 

Any help appreciated and some explanation on the pins used explicitly for the Xplained Pro Board.

**Comment by gd91** [comment]
No the place for technical support. Check out www.microchip.com/support
